dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: sfzt+MsKngphs1Xth8SsP3z0YfOscB7uBu8gE7vkO/oMheqzArqvr1Wl73q8j7eQ7UnKmoysrYsukk663mUkgdWmmjDkMRpV1NmHUhYmi4nZPx3jRc0qXBf0h51cFwSp/nZI+M4Km2QHExXLq2i2cdhfRxyd2Mw89LRGyycALLC4xjp5OGyPVwAqOwxI5pBuUWN4vEddbs7peCb5NEZQZsG6Rt6UUl+JQU7RfpV7yYIEsy2bthMZHggz7So+DO5RD0fXL9o2SwwZ9YMIMkSsSJn/FVn2j8Q+Vg3Hl8c4icY1JynNdKoIFTgXEG649sekiYt2C8hjOgtZRWCh6NS/kXtu+v4yTk7Qr1zOlUV4NlP8VB0rnRTwaj/T6kOPXDfOGdQUwtuKEMwJ2zt0VfXQWwjC8quO+ohlH5oWbUesS1wdAgbWCOnX6QKNQRygRomABDzdhZ/lWuTOhqsiGQL74oa6SmmWJwBBo3LzVNsZt5+9uBFwxltZfv9wQ8CVIrB8X6uuUly1phGszvkWt+toAOas+CK2oiJGUe575bNWVyfzUY8eGQWBF3pNev/PTzzboFfkxUIChQMJpZnD7iHcYMm/xm+Um+d9/gOglVksIb+eW84svoDiWIxIk+509cwwQWAkJmgp8rGvAP6SU7xmBnhmF/Ml9lUGYn/pW6eU8kY=
